### DISCUSSION TITLE
Data Table Pagination on top

### DISCUSSION THREAD

**Discussion by kellerza** [tusen-ai/naive-ui#5106] [Q&A] [answered]
Is there any way to move the pagination control to the top of the data table?

**Comment by sahitono** [comment, marked as answer]
maybe with reversing the order through css, set style like this `display: flex; flex-direction: column-reverse;`

**Reply by kellerza** [reply]
Thank you, that did the trick!

```css
.n-data-table { display: flex; flex-direction: column-reverse; }
```

I do feel a bit like [this](https://www.youtube.com/watch?v=Gdr7DCakdcU) guy 😄
