### DISCUSSION TITLE
自定义的样式变量，如何处理使用时的类型错误？

### DISCUSSION THREAD

**Discussion by vaseala** [tusen-ai/naive-ui#7043] [Q&A]
js
```js
const overrides = ref({
  common: {
    bodyColor: '#FAFAFA',
    rowBgColor: 'red',
  },
})
```

html
```html
<n-config-provider :theme-overrides="overrides">
</n-config-provider>
```

useage in css code
```css
.selector{
  background-color: v-bind('themeVars.rowBgColor');
}
```

![image](https://github.com/user-attachments/assets/81b06815-8bc6-4a39-a3d5-96c85871a2c8)
