### ISSUE TITLE
如何引用主题变量

### ISSUE THREAD

**Issue by yetrun** [tusen-ai/naive-ui#4030]
想编写一个边框，需要引用组件库的主题变量以保证风格的一致性。Element 库可以向下面这样引用：

```css
aside { border-right: 1px solid var(--el-border-color) }
```

请问下 naive 库有什么提供的方案吗？
