### ISSUE TITLE
Skeleton 能新增自訂義顏色嗎？

### ISSUE THREAD

**Issue by JarvisChao** [tusen-ai/naive-ui#5410]
### This function solves the problem (这个功能解决的问题)
讓色塊不只是預設顏色
### Expected API (期望的 API)
```html
<n-skeleton color-start="#" color-end="#" />
```

或直接更改 css
```css
:root {
  --n-color-start: #
  --n-color-start: #
}
```
